[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 1000

[invariant]
depth = 20
runs = 1000
fail_on_revert = true
shrink_run_limit = 0

[rpc_endpoints]
blast_sepolia = "${BLAST_SEPOLIA_URL}"

[etherscan]
blast_sepolia = { key = "${BLASTSCAN_API_KEY}", url = "https://api-sepolia.blastscan.io/api", chain = 168587773 }
sepolia = { key = "${ETHERSCAN_KEY}" }
optimism_sepolia = { key = "${OPTIMISMSCAN_KEY}" }